sudo: false
language: php
php:
  - 7.1

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer global require phpunit/phpunit:^7.4
  - composer install

script:
  - $HOME/.composer/vendor/bin/phpunit
  - ./vendor/bin/phpcs ./ --standard=./phpcs.config.xml
